services:
  - type: web
    name: academic-issue-tracker
    env: python
    buildCommand: rm -rf frontend/node_modules && rm -f frontend/package-lock.json && cd frontend && npm install && npm run build && cd .. && mkdir -p backend/templates && cp frontend/dist/index.html backend/templates/index.html && cd backend && pip install -r ../requirements.txt && python backend/manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: academic_issue_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: EMAIL_HOST_USER
        value: emmasonmutsaka@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: ALLOWED_HOSTS
        value: academic-issue-tracking-system-3-qvmp.onrender.com,localhost,127.0.0.1
      - key: PYTHON_VERSION
        value: 3.9.18 # Or your specific Python version

databases:
  - name: academic_issue_db
    databaseName: academic_issue_db
    user: academic_issue_user
