services:
  - type: web
    name: academic-issue-tracker
    env: python
    buildCommand: cd frontend && npm rimraf node_modules package-lock.json && npm install && npm run build && cd .. && mkdir -p backend/templates && cp frontend/dist/index.html backend/templates/index.html && cp -r frontend/dist/assets backend/templates/assets/ && cd backend && pip install -r ../requirements.txt 
    startCommand: gunicorn backend.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: academic_issue_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: EMAIL_HOST_USER
        value: emmasonmutsaka@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: ALLOWED_HOSTS
        value: "academic-issue-tracking-system-3-qvmp.onrender.com,localhost,127.0.0.1"
      - key: PYTHON_VERSION
        value: 3.9.18

databases:
  - name: academic_issue_db
    databaseName: academic_issue_db
    user: academic_issue_user
