services:
  - type: web
    name: academic-issue-tracker
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: academic_issue_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: EMAIL_HOST_USER
        value: emmasonmutsaka@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: ALLOWED_HOSTS
        value: .render.com

databases:
  - name: academic_issue_db
    databaseName: academic_issue_db
    user: academic_issue_user
