# Generated by Django 5.1.7 on 2025-03-18 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_customuser_college_customuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='academicYear',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='courseCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issueDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='lecturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='studentId',
            field=models.CharField(default='DEFAULT_STUDENT_ID', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='studentName',
            field=models.CharField(default='Default Student Name', max_length=255),
            preserve_default=False,
        ),
    ]
