# Generated by Django 5.1.7 on 2025-03-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_issue_academicyear_issue_coursecode_issue_issuedate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_department',
            new_name='department',
        ),
    ]
