# Generated by Django 5.1.7 on 2025-03-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_rename_issue_department_issue_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='department',
            new_name='Issue_department',
        ),
    ]
