# Generated by Django 5.1.7 on 2025-03-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_rename_department_issue_issue_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='Issue_department',
            new_name='issue_department',
        ),
    ]
