# Generated by Django 5.1.7 on 2025-03-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_rename_issue_department_issue_issue_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_department',
            new_name='department',
        ),
    ]
