# Generated by Django 5.1.7 on 2025-04-03 06:43

from django.db import migrations, models

<<<<<<< HEAD
class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
=======

class Migration(migrations.Migration):

    dependencies = [
>>>>>>> 04c33485d80eae37a63dced6318b363e38c60b23
        ('issues', '0010_rename_issue_department_issue_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='issueattachment',
            name='uploaded_at',
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='customuser',
            name='courses_taught',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_groups', related_query_name='customuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customuser_user_permissions', related_query_name='customuser', to='auth.permission', verbose_name='user permissions'),
        ),

        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='no-reply@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='studentId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
