# Generated by Django 5.1.7 on 2025-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_rename_issue_department_issue_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='issueattachment',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='no-reply@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='studentId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
