# Generated by Django 5.1.7 on 2025-04-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('issues', '0011_remove_auditlog_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='is_read',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_users', related_query_name='customuser', to='auth.group', verbose_name='groups'),
        ),
    ]
