# Generated by Django 5.1.7 on 2025-04-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_rename_is_read_notification_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
