# Generated by Django 5.2 on 2025-04-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_rename_is_read_notification_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='courses_taught',
        ),
    ]
