# Generated by Django 5.2 on 2025-04-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0014_remove_customuser_courses_taught'),
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
           model_name='customuser',
           name='courses_taught',
           field=models.TextField(blank=True, null=True),
       ),
=======
            model_name='customuser',
            name='courses_taught',
            field=models.TextField(blank=True, null=True),
        ),
>>>>>>> 52e82d4adae58a419d7a22b9ecf2e1c9764f993f
        migrations.AddField(
            model_name='issue',
            name='college',
            field=models.CharField(blank=True, max_length=255, null=True),
<<<<<<< HEAD
       ),
=======
        ),
>>>>>>> 52e82d4adae58a419d7a22b9ecf2e1c9764f993f
    ]
