# Generated by Django 5.2 on 2025-04-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0014_issue_college'),
        ('issues', '0014_remove_customuser_courses_taught'),
    ]

    operations = [
    ]
