# Generated by Django 5.2 on 2025-04-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_merge_20250407_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses_taught',
            field=models.TextField(blank=True, null=True),
        ),
    ]
