# Generated by Django 5.2 on 2025-04-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_customuser_courses_taught_issue_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='studentRegNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
