# Generated by Django 5.2 on 2025-04-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_customuser_courses_taught_issue_college'),
        ('issues', '0016_customuser_courses_taught'),
    ]

    operations = [
    ]
