# Generated by Django 5.2 on 2025-04-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_alter_customuser_studentregnumber'),
        ('issues', '0017_merge_20250408_1648'),
    ]

    operations = [
    ]
